name: GitHub Actions Demos
run-name: ${{ github.actor }} is testing
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Here is the message in GitHub Actions"

      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Building
        run: npm run build

      - name: Run tests
        run:  npm run test -- src/utils/double.test.ts

      - name: Congrats!
        if: success()
        run: echo "Everything is OK!"

      - name: Sorry!
        if: failure()
        run: echo "Something wrong happened!"
